### ISSUE TITLE
SSM --> StateSpaceDynamics

### ISSUE THREAD

**Issue by briandepasquale** [depasquale-lab/StateSpaceDynamics.jl#24]
@rsenne Pretty much all instances of `SSM` need to be changed to `StateSpaceDynamics`. I did this for the tests, but in the src is a different story. Just an FYI.

**Comment by rsenne** [comment]
I can take care of this

**Comment by rsenne** [comment]
Checked through all the source can't find any instances outside of comments. Gonna close this issue.
